services:
  - type: web
    name: personal-budget-tracker
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: SERVER_PORT=8080 node server.js
    preDeployCommand: cp .env.render .env
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false 